---
fqdn: tr1d1um
env: test
scheme: http
hooksScheme: http

primary:
  address: ":6100"
health:
  address: ":6101"
  options:
    - "PayloadsOverZero"
    - "PayloadsOverHundred"
    - "PayloadsOverThousand"
    - "PayloadsOverTenThousand"
  readTimeout: "15s"
  idleTimeout: "15s"
pprof:
  address: ":6102"
  readTimeout: "15s"
  idleTimeout: "15s"
metric:
  address: ":6103"
  metricsOptions:
    namespace: "webpa"
    subsystem: "tr1d1um"
  readTimeout: "15s"
  idleTimeout: "15s"

log:
  file: "stdout"
  level: "INFO"
  json: false
  reducedLoggingResponseCodes: [200, 504]

webhookStore:
  bucket: webhooks
  address: http://argus:6600
  pullInterval: 5s
  auth:
    Basic: Basic dXNlcjpwYXNz

authHeader: ["dXNlcjpwYXNz"]
targetURL: http://scytale:6300
WRPSource: "dns:tr1d1um.example.net"
supportedServices:
  - "config"
clientTimeout: "135s"
respWaitTimeout: "129s"
netDialerTimeout: "5s"
requestRetryInterval: "2s"
requestMaxRetries: 2
